#-------------------------------
# General Site Settings

title: Andreas Altendorfer
description: Software Craftsman
email: andreas@altendorfer.at

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Developer, url: '#developer'}
- {name: Contact, url: '#contact'}

layout:
  logo: 'hero-bg.png'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: "A Developer's Blog"
  rel-author: 'https://plus.google.com/u/0/+AndreasAltendorfer/'
  rel-publisher: 'https://plus.google.com/u/0/+AltendorferAT/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Andi is a software craftsman** with three decades of experience.


skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '6'}
- {name: Architecture, value: '9'}
- {name: TDD & Clean Code, value: '10'}
- {name: Object Oriented Programming, value: '9'}
- {name: Functional Programming, value: '5'}

#-------------------------------
# Work Section

projects:
- {name: NET-AT-WORK, folder: 'proj-1', file: 'work/proj-2.html'}
- {name: ÖBB Telekom, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Ärztekammer NÖ, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Distance Learning Environment, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Runtastic, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: CGM, folder: 'proj-6', file: 'work/proj-6.html'}


#-------------------------------
# Clients Section

clients:
- {avatar: 'turbo_pascal.jpg',
  name: 'Turbo Pascal',
  title: 'Starting first commercial programming in 1986',
  quote: '<p><strong>In 1986 Andreas started his first commercial programming</strong>. A two floppy disc based application for a second-hand-shop. Written in Pascal. DOS, Pascal, B-Tree Datastore.</p>',
  logo: 'logo1.png'}
- {avatar: 'ruby_and_rails.jpg',
  name: 'Ruby, RAIL',
  title: '8 years with Ruby and RAILS',
  quote: '<p><strong>From 2007 to 2014, aCampus Distance Learning System</strong>.</p>',
  logo: 'logo2.png'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/Nickendell'}
- {icon: 'google', link: 'https://plus.google.com/+AndreasAltendorfer'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UChH6ka-7pLeiqOIFfyqBE0w'}
- {icon: 'linkedin', link: 'https://at.linkedin.com/in/andreasaltendorfer'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
